### ISSUE TITLE
`TypeError: a bytes-like object is required, not 'str'` during `docker-compose up`

### ISSUE THREAD

**Issue by Iambecomeroot** [grocy/grocy-docker#26]
I cloned this repo and ran `docker-compose pull` then `docker compose up`.

Here is the output:
```
Removing grocy-nginx
Recreating grocy ... done
Recreating 7cf5bd99b9fc_grocy-nginx ...

ERROR: for 7cf5bd99b9fc_grocy-nginx  a bytes-like object is required, not 'str'

ERROR: for grocy-nginx  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/b06e81bc218cfab614b27afb471d5abef54f5b6dbdf872d2b9131d25e1a856f9/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 625, in start_container
    container.start()
  File "/usr/lib/python3.8/site-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint grocy-nginx (08a432792f7c28033186b9de3b055ab8f561dd38ce6984f4b150f04c3c8b3688): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3.8/site-packages/compose/project.py", line 565, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3.8/site-packages/compose/project.py", line 548, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 561, in execute_convergence_plan
    return self._execute_convergence_recreate(
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 486, in _execute_convergence_recreate
    containers, errors = parallel_execute(
  File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 481, in recreate
    return self.recreate_container(
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 602, in recreate_container
    self.start_container(new_container)
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 627, in start_container
    if "driver failed programming external connectivity" in ex.explanation:
TypeError: a bytes-like object is required, not 'str'
```

`docker --version`:
```
Docker version 19.03.5-ce, build 633a0ea838
```

`docker-compose --version`:
```
docker-compose version 1.25.0, build unknown
```

`uname -a`:
```
Linux robitaille.host 5.4.2-arch1-1 #1 SMP PREEMPT Thu, 05 Dec 2019 12:29:40 +0000 x86_64 GNU/Linux
```

**Comment by talmai** [comment]
You might want to start diagnosing this> bind: address already in use---- On Fri, 06 Dec 2019 18:50:29 -0500  Marcel Robitaille<notifications@github.com> wrote ----I cloned this repo and ran docker-compose pull then docker compose up. 
Here is the output: 
Removing grocy-nginx 
Recreating grocy ... done 
Recreating 7cf5bd99b9fc_grocy-nginx ... 
 
ERROR: for 7cf5bd99b9fc_grocy-nginx  a bytes-like object is required, not 'str' 
 
ERROR: for grocy-nginx  a bytes-like object is required, not 'str' 
Traceback (most recent call last): 
  File "/usr/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status 
    response.raise_for_status() 
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status 
    raise HTTPError(http_error_msg, response=self) 
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/b06e81bc218cfab614b27afb471d5abef54f5b6dbdf872d2b9131d25e1a856f9/start 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 625, in start_container 
    container.start() 
  File "/usr/lib/python3.8/site-packages/compose/container.py", line 241, in start 
    return self.client.start(self.id, **options) 
  File "/usr/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped 
    return f(self, resource_id, *args, **kwargs) 
  File "/usr/lib/python3.8/site-packages/docker/api/container.py", line 1095, in start 
    self._raise_for_status(res) 
  File "/usr/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status 
    raise create_api_error_from_http_exception(e) 
  File "/usr/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception 
    raise cls(e, response=response, explanation=explanation) 
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint grocy-nginx (08a432792f7c28033186b9de3b055ab8f561dd38ce6984f4b150f04c3c8b3688): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use'") 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/usr/bin/docker-compose", line 11, in <module> 
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')() 
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 72, in main 
    command() 
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 128, in perform_command 
    handler(command, command_options) 
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 1107, in up 
    to_attach = up(False) 
  File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 1088, in up 
    return self.project.up( 
  File "/usr/lib/python3.8/site-packages/compose/project.py", line 565, in up 
    results, errors = parallel.parallel_execute( 
  File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 112, in parallel_execute 
    raise error_to_reraise 
  File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 210, in producer 
    result = func(obj) 
  File "/usr/lib/python3.8/site-packages/compose/project.py", line 548, in do 
    return service.execute_convergence_plan( 
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 561, in execute_convergence_plan 
    return self._execute_convergence_recreate( 
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 486, in _execute_convergence_recreate 
    containers, errors = parallel_execute( 
  File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 112, in parallel_execute 
    raise error_to_reraise 
  File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 210, in producer 
    result = func(obj) 
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 481, in recreate 
    return self.recreate_container( 
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 602, in recreate_container 
    self.start_container(new_container) 
  File "/usr/lib/python3.8/site-packages/compose/service.py", line 627, in start_container 
    if "driver failed programming external connectivity" in ex.explanation: 
TypeError: a bytes-like object is required, not 'str' 
 
docker --version: 
Docker version 19.03.5-ce, build 633a0ea838 
 
docker-compose --version: 
docker-compose version 1.25.0, build unknown 
 
uname -a: 
Linux robitaille.host 5.4.2-arch1-1 #1 SMP PREEMPT Thu, 05 Dec 2019 12:29:40 +0000 x86_64 GNU/Linux

**Comment by talmai** [comment]
(Let me try reducing the amount of text in my reply)You might want to start diagnosing this the port issue ("bind: address already in use").

**Comment by Iambecomeroot** [comment]
I know this isn't helpful but I ran `docker-compose up` today and it just worked. I don't know what changed but it's working now.

**Comment by MarcHarriss** [comment]
experienced the same issue, make sure you don't have another container using the same port that this requires

**Comment by MateusMarcuzzo** [comment]
So, how do you  solve it?

**Comment by wwcdg** [comment]
> 遇到同样的问题，请确保您没有另一个容器使用这需要的相同端口

This is right
